name: CMake Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-all-dev libssl-dev  # Add other Linux deps here

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install boost boost-build openssl@3 # Add other macOS deps here


      - name: Configure CMake
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release ${{ if eq(runner.os, 'windows-2019') then '-Thost=x64 -G "Visual Studio 16 2019" -A x64' else '' endif }}

      - name: Build
        working-directory: build
        shell: bash
        run: |
          if [[ ${{ runner.os }} == 'windows-2019' ]]; then
            cmake --build . --config Release -- /m
          else
            cmake --build . --config Release
          fi