name: CMake Build

on:
  push:
    branches: [ "master" ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # Checkout submodules
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libboost-all-dev libssl-dev
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: Build
        working-directory: build
        run: cmake --build . --config Release

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # Checkout submodules
      - name: Install dependencies
        run: |
          brew install boost boost-build openssl@3
      - name: Configure CMake
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
      - name: Build
        working-directory: build
        run: cmake --build . --config Release


  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive # Checkout submodules
      - name: Install dependencies
        shell: pwsh
        run: |
          choco install -y openssl
      - name: Install boost
        uses: MarkusJx/install-boost@v2.4.5
        id: install-boost # Important: Set an ID for the step
        with:
          boost_version: 1.74.0 # or 1.74.0 as you need
          toolset: msvc
          platform_version: 2019  # Or whichever you are using
      - name: Configure CMake
        shell: bash
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -A x64
        env:
          BOOST_ROOT: ${{ steps.install-boost.outputs.BOOST_ROOT }}
      - name: Build
        working-directory: build
        shell: bash  # Important to keep bash here for consistency
        run: cmake --build . --config Release